config/routes.rb
Rails.application.routes.draw do
  resources :event

  root 'event#new'

end

app/models/eventdate.rb
class Eventdate < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
  	event = Eventdate.all
  	#event = Eventdate.all
  	render json:event

  end
  def new
  	@event = Eventdate.new
  end
  def create
   p '.................'
  	@event = Eventdate.new(eventdate_params)
  	@event.save
  	redirect_to root_path
   end
   private

   def eventdate_params 
   	 params.require(:eventdate).permit(:title,:start,:end)
   	end
 end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/event/new.html.erb
 <div id='calendar'></div>
<div id="myModal"  class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= form_for :eventdate, url: event_index_path do |f| %>
  <p>
    <%= f.label :title%><br>
    <%= f.text_area :title%>
  </p>
 
  <p>
    <%= f.label :start%><br>
    <%= f.date_field :start %>
  </p>
  <p>
    <%= f.label :end%><br>
    <%= f.date_field :end %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
       $(document).ready(function() {

         // page is now ready, initialize the calendar...

         $('#calendar').fullCalendar({
          dayClick: function(){
            
            
            $('#myModal').modal()        

          },

          events: '/event'          

        });

        });
	  
	
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>